server:
  port: ${PORT:8080}
logging:
  level:
    '[com.vaadin.azure]': debug
spring:
  redis:
    host: azure-kit-redis-service
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
  azure:
    hazelcast:
      kubernetes:
        xxxservice-name: azure-kit-hazelcast-service
  serialization:
    include-packages: com.vaadin.azure.demo
  devmode:
    sessionSerialization:
      enabled: true



